display_extenders:
  simple_sitemap_display_extender: simple_sitemap_display_extender
ui:
  show:
    performance_statistics: true
    sql_query:
      enabled: true
field_rewrite_elements:
  div: DIV
  span: SPAN
  h1: H1
  h2: H2
  h3: H3
  h4: H4
  h5: H5
  h6: H6
  p: P
  header: HEADER
  footer: FOOTER
  article: ARTICLE
  section: SECTION
  aside: ASIDE
  details: DETAILS
  blockquote: BLOCKQUOTE
  figure: FIGURE
  address: ADDRESS
  code: CODE
  pre: PRE
  var: VAR
  samp: SAMP
  kbd: KBD
  strong: STRONG
  em: EM
  del: DEL
  ins: INS
  q: Q
  s: S
